# Jekyll configuration for hooked-api GitHub Pages site
title: Hooked API
description: Build extensible APIs with hooks, plugins, and scopes
theme: jekyll-theme-cayman
baseurl: "/json-rest-api2"
url: "https://mobily-enterprises.github.io"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# GitHub repository information (update with your actual repo)
github:
  repository_url: https://github.com/mobily-enterprises/json-rest-api2
  owner_name: mobily-enterprises
  repository_name: json-rest-api2